"""maimaiDX 查分核心逻辑（不依赖 MaiBot SDK，可独立测试）。"""

from .model import (
    DIFF_NAMES,
    AliasItem,
    APIResult,
    BasicInfo,
    Chart,
    Music,
    PlayChart,
    PlayRecord,
    Stats,
    UserCharts,
    UserInfo,
    UserInfoDev,
)

from . import extra as mai_extra

from .api import (
    DivingFishOAuth,
    DivingFishScope,
    MaimaiAPI,
    MaimaiError,
    MusicNotPlayError,
    OAuthBindingMismatchError,
    OAuthConfirmationCodeError,
    OAuthError,
    OAuthNotBoundError,
    SCOPE_NAMES,
    SCOPE_VALUES,
    ServerError,
    TokenDisableError,
    TokenError,
    TooManyRequestsError,
    UnknownError,
    UserDisabledQueryError,
    UserNotExistsError,
    UserNotFoundError,
    binding_label,
    parse_scope,
)
from .music import AliasList, MaiMusic, MusicList
from .format import format_b50, format_player_record, format_search_list, format_song_brief, format_song_info, paginate

__all__ = [
    'DIFF_NAMES',
    'AliasItem',
    'APIResult',
    'BasicInfo',
    'Chart',
    'Music',
    'PlayChart',
    'PlayRecord',
    'Stats',
    'UserCharts',
    'UserInfo',
    'UserInfoDev',
    'mai_extra',
    'DivingFishOAuth',
    'DivingFishScope',
    'MaimaiAPI',
    'MaimaiError',
    'MusicNotPlayError',
    'OAuthBindingMismatchError',
    'OAuthConfirmationCodeError',
    'OAuthError',
    'OAuthNotBoundError',
    'SCOPE_NAMES',
    'SCOPE_VALUES',
    'ServerError',
    'TokenDisableError',
    'TokenError',
    'TooManyRequestsError',
    'UnknownError',
    'UserDisabledQueryError',
    'UserNotExistsError',
    'UserNotFoundError',
    'binding_label',
    'parse_scope',
    'AliasList',
    'MaiMusic',
    'MusicList',
    'format_b50',
    'format_player_record',
    'format_search_list',
    'format_song_brief',
    'format_song_info',
    'paginate',
]
